### PR TITLE
Fix AU warning label not showing issue

### LINKED ISSUE #2318: [IntelliJ][Spark on ADL] The warning message in update dialog might need update
Build: Develop 844

Repro Steps:
1. Create a serverless cluster, right click on cluster then click "Update"
2. Update "Number of Containers" to make the "AU Required" > "Available AU"
3. Click OK, the warning icon displays
4. Hover on the warning icon, check the warning message

Result:
It is update dialog, the message says provisioning might need update
image

### PR DESCRIPTION
**Pull request by t-rufang**
To fix #2318 and #2283

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/sparkserverless/serverexplore/ui/SparkServerlessClusterUpdateDialog.java [hunk 1]
```diff
@@ -22,32 +22,30 @@
...
-import org.apache.commons.lang3.StringUtils;
 
 import java.awt.event.WindowAdapter;
 import java.awt.event.WindowEvent;
-import java.time.LocalDateTime;
 
 public class SparkServerlessClusterUpdateDialog extends SparkServerlessProvisionDialog implements ILogger {
     @NotNull
     private SparkServerlessClusterUpdateCtrlProvider ctrlProvider;
+    private static final String auWarningTip = "Currently, there are not enough available AU for your serverless cluster Updating. Please adjust your cluster configuration or the updating request will be submitted into the queue with PENDING status.";
```
Comment (wezhang) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/sparkserverless/serverexplore/ui/SparkServerlessClusterUpdateDialog.java]:
```suggestion
    private static final String AU_WARNING_TIP = "Currently, there are not enough available AU for your serverless cluster Updating. Please adjust your cluster configuration or the updating request will be submitted into the queue with PENDING status.";
```

Comment (wezhang) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/sparkserverless/serverexplore/ui/SparkServerlessClusterUpdateDialog.java]: Upper case characters for static final val.

**Comment by wezhang** [comment]
```
> Task :compileJava
warning: Supported source version 'RELEASE_7' from annotation processor 'com.microsoft.azure.management.apigeneration.LangDefinitionProcessor' less than -source '1.8'
/jenkinshome/jenkins/workspace/Azure_Toolkits_for_Java/AzureToolsManager_PR/PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/sparkserverless/serverexplore/ui/SparkServerlessClusterUpdateDialog.java:48: error: cannot find symbol
        this.auWarningLabel.setToolTipText(auWarningTip);
                                           ^
  symbol:   variable auWarningTip
  location: class SparkServerlessClusterUpdateDialog
Note: Some input files use or override a deprecated API.
```
