### PR TITLE
#6476: avoid long time I/O in predicate of actions.

### LINKED ISSUE #6476: [IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper, id=action.vm.add_ssh_configuration) with text=Add SSH Configuration reactor.core.Exceptions$ReactiveException: java.io.IOException: Operation timed out
IntelliJ build version: 2021.3.2 IU-213.6777.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.62.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1512x877,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@a29c416,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper, id=action.vm.add_ssh_configuration) with text=Add SSH Configuration, throwable=reactor.core.Exceptions$ReactiveException: java.io.IOException: Operation timed out
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at com.microsoft.azure.toolkit.lib.compute.vm.VirtualMachine.getHostIp(VirtualMachine.java:88)
	at com.microsoft.azure.toolkit.lib.compute.vm.VirtualMachine.isSshEnabled(VirtualMachine.java:83)
	at com.microsoft.azure.toolkit.intellij.vm.IntelliJVMActionsContributorForUltimate.lambda$registerHandlers$1(IntelliJVMActionsContributorFo

### PR DESCRIPTION
**Pull request by wangmingliang-ms**
What does this implement/fix? Explain your changes.
---------------------------------------------------
* Avoid long time I/O in predicate of actions. 
* Catch the exception and show as an error notification.

Does this close any currently open issues?
------------------------------------------
#6476: [IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper, id=action.vm.add_ssh_configuration) with text=Add SSH Configuration reactor.core.Exceptions$ReactiveException: java.io.IOException: Operation timed out 

Any relevant logs, screenshots, error output, etc.?
-------------------------------------

Any other comments?
-------------------
…

Has this been tested?
---------------------------
- [ ] Tested

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/azure-intellij-plugin-vm/src/main/java/com/microsoft/azure/toolkit/intellij/vm/ssh/AddSshConfigAction.java [hunk 1]
```diff
@@ -31,6 +31,9 @@
 public class AddSshConfigAction {
 
     public static void addSshConfig(VirtualMachine vm, @Nonnull Project project) {
+        if (!vm.isSshEnabled()) {
+            AzureMessager.getMessager().warning(String.format("ssh is not enabled on '%s'", vm.getName()));
+        }
```
Comment (wangmingliang-ms) [inline PluginsAndFeatures/azure-toolkit-for-intellij/azure-intellij-plugin-vm/src/main/java/com/microsoft/azure/toolkit/intellij/vm/ssh/AddSshConfigAction.java:37]: should `return`;

Comment (wangmingliang-ms) [reply PluginsAndFeatures/azure-toolkit-for-intellij/azure-intellij-plugin-vm/src/main/java/com/microsoft/azure/toolkit/intellij/vm/ssh/AddSshConfigAction.java:37]: `SSH`

**Review by Flanker32 — APPROVED** [review]
LGTM
