### PR TITLE
Disable interactive console for cosmos serverless run config

### LINKED ISSUE #2648: [IntelliJ][Spark][serverless][console]Start livy interactive console with serverless config get errors, need update
Build: Private 2641

Repro Steps:
1. Create serverless config file
2. Start livy interactive session console

Result:
image

Expect: 
Provide meaningful message.

### PR DESCRIPTION
**Pull request by konjac**
To fix #2648

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkScalaLivyConsoleAction.kt [hunk 1]
```diff
@@ -22,12 +22,32 @@
...
 
-class RunSparkScalaLivyConsoleAction : RunSparkScalaConsoleAction(), ILogger {
+class RunSparkScalaLivyConsoleAction : RunSparkScalaConsoleAction() {
     override val consoleRunConfigurationFactory: ScalaConsoleRunConfigurationFactory
         get() = SparkScalaLivyConsoleConfigurationType().confFactory()
 
     override fun getNewSettingName(): String = "Spark Livy Interactive Session Console(Scala)"
+
+    override fun update(event: AnActionEvent) {
+        super.update(event)
```
Comment (wezhang) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkScalaLivyConsoleAction.kt]: It might be better to disable it firstly at beginning:
`event.presentation.isEnabled = false`

Otherwise, the following return when project is null will cause the presentation is enabled by default.

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkConsoleActionDelegate.kt [hunk 2]
```diff
@@ -52,6 +52,7 @@ open class RunSparkConsoleActionDelegate(sparkScalaActionClassName: String) : Az
         }
     }
 
+
```
Comment (wezhang) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkConsoleActionDelegate.kt]: The white space change can be reverted

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/action/SelectSparkApplicationTypeAction.kt [hunk 3]
```diff
@@ -42,6 +47,16 @@ abstract class SelectSparkApplicationTypeAction
...
         }
+
+        @JvmStatic
+        fun getRunConfigurationType() : ConfigurationType? {
+            return when(getSelectedSparkApplicationType()) {
+                SparkApplicationType.None -> null
+                SparkApplicationType.HDInsight -> LivySparkBatchJobRunConfigurationType.getInstance()
+                SparkApplicationType.CosmosSpark -> CosmosSparkConfigurationType
+                SparkApplicationType.CosmosServerlessSpark -> CosmosServerlessSparkConfigurationType
+            }
```
Comment (wezhang) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/action/SelectSparkApplicationTypeAction.kt]: Do you need an `else -> null`?

Comment (konjac) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/action/SelectSparkApplicationTypeAction.kt]: All possible cases are covered in the branches. else branch is not necessary.

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkScalaLivyConsoleAction.kt [hunk 4]
```diff
@@ -22,12 +22,33 @@
...
 
     override fun getNewSettingName(): String = "Spark Livy Interactive Session Console(Scala)"
+
+    override fun update(event: AnActionEvent) {
+        event.presentation.isEnabled = false
+        super.update(event)
+        val project = CommonDataKeys.PROJECT.getData(event.dataContext) ?: return
+        val selectedConfigSettings = RunManagerEx.getInstanceEx(project).selectedConfiguration
+        var runConfig = selectedConfigSettings?.configuration
+
```
[the remark this answers is not in the document]
Comment (konjac) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkScalaLivyConsoleAction.kt]: For example, the user sets the run config type to None but he selects an HDI config. Then we should launch livy console with HDI config rather than disabling the entry.

[the remark this answers is not in the document]
Comment (konjac) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkScalaLivyConsoleAction.kt]: Emm, code logic related to getRunConfigurationType() should go to another PR. In fact, it is for local console when no run config is selected.
