### PR TITLE
Fix blocked issue for spark interactive console

### LINKED ISSUE #2424: [IntelliJ]Need add status message since it takes too long for livy interactive console.
Build:
azure-toolkit-for-intellij-183.4284.118.develop.880.11-29-2018.zip
intelliJ 2018.3.1 RC2

Repro Steps:
1. Open a scala file, run livy interactive console

Result:
It would take a long time to end the process. 
The status bar will show that the process is running.

### PR DESCRIPTION
**Pull request by konjac**
Fixes #2424

This PR made the starting progress unblocking. Console will launch first and then session handler will continue to connect livy in the background.

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunProfileState.kt [hunk 1]
```diff
@@ -44,25 +47,24 @@ class SparkScalaLivyConsoleRunProfileState(private val consoleBuilder: SparkScal
...
-            prompt = "\nSpark>"
-        }
 
         val livySessionProcessHandler = SparkLivySessionProcessHandler(SparkLivySessionProcess(session))
 
         console.attachToProcess(livySessionProcessHandler)
-        livySessionProcessHandler.execute(postStartCodes)
+
+        session.create()
+                .subscribeOn(Schedulers.io())
```
Comment (wezhang) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunProfileState.kt]: Could you try to replace the scheduler with `IdeaSchedulers.processBarVisibleAsync()`, which can show the progress in the status bar?

Comment (konjac) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunProfileState.kt]: Opened issue #2465 to track this
