### PR TITLE
Fix init multi times issue

### LINKED ISSUE #4469: Pop up create app dialog again after input app name and click ok
### **Environment:**

- OS: Win 10
- IDE: IC19.3 - jre8
- Plugins Version: Azure java toolkits for IntelliJ 3.38.0

### **Repro Steps：**
1, Open spring boot project
2, Right click your project select Azure -> Deploy to spring cloud
3. New a app name, click ok

### **Actual result:**
Pop up create app dialog again after input app name and click ok 
image

### PR DESCRIPTION
**Pull request by Flanker32**
Fix init multi times issue fixes #4469

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/springcloud/ui/SpringCloudAppSettingPanel.java [hunk 1]
```diff
@@ -179,35 +182,41 @@ private void init() {
         cbSubscription.addItem(CommonConst.REFRESH_TEXT);
     }
 
-    private void initCluster(String initialValue) {
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/springcloud/ui/SpringCloudAppSettingPanel.java:182]: do we need to use isClusterInitialized to guard the initialization? it is only called from ctor.

Comment (andxu) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/springcloud/ui/SpringCloudAppSettingPanel.java:182]: got it, since a prev PR change the calling place.
