### PR TITLE
Bug Fix #4720 & #4885 Subscription Selection Related Issues.

### LINKED ISSUE #4720: Allow Select All/None in Subscription Selection Dialog
Screen Shot 2020-11-05 at 3 01 55 PM

Usually, there's a checkbox to allow select all or none given the list could be very long. You can find examples very easily:
image

### PR DESCRIPTION
**Pull request by shenqianjin**
Critical issues, PR into this release branch.

Partial selected:
image

Selected All:
image

Selected None:
image

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java [hunk 1]
```diff
@@ -82,11 +81,16 @@ public void update(AnActionEvent e) {
...
         final SubscriptionManager subscriptionManager = manager.getSubscriptionManager();
-
-        return loadSubscriptions(subscriptionManager, project)
+        List<SubscriptionDetail> subs = subscriptionManager.getSubscriptionDetails();
+        SubscriptionsDialog d = SubscriptionsDialog.go(subs, project);
+        if (Objects.nonNull(d)) {
+            subscriptionManager.setSubscriptionDetails(subs);
+        }
+        return Single.fromCallable(() -> subs);
+        /*return loadSubscriptions(subscriptionManager, project)
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java:90]: return Single.just(subs)?

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java [hunk 2]
```diff
@@ -82,11 +81,16 @@ public void update(AnActionEvent e) {
...
             .switchMap((subs) -> selectSubscriptions(project, subs))
             .toSingle()
-            .doOnSuccess((subs) -> Optional.ofNullable(subs).ifPresent(subscriptionManager::setSubscriptionDetails));
+            .doOnSuccess((subs) -> Optional.ofNullable(subs).ifPresent(subscriptionManager::setSubscriptionDetails));*/
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java:93]: don't allow this kind of comments

Comment (shenqianjin) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java]: removed

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java (hunk 1 above)
Comment (shenqianjin) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java]: updated.

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java [hunk 3]
```diff
@@ -82,11 +81,12 @@ public void update(AnActionEvent e) {
         }
 
         final SubscriptionManager subscriptionManager = manager.getSubscriptionManager();
-
-        return loadSubscriptions(subscriptionManager, project)
-            .switchMap((subs) -> selectSubscriptions(project, subs))
-            .toSingle()
-            .doOnSuccess((subs) -> Optional.ofNullable(subs).ifPresent(subscriptionManager::setSubscriptionDetails));
+        List<SubscriptionDetail> subs = subscriptionManager.getSubscriptionDetails();
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java:84]: you cannot convert async loadSubscriptions to sync in ui thread, this will block ui

Comment (shenqianjin) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java:84]: in fact the original codes is also blocking until the async task completes.

Comment (andxu) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java:84]: AzureTaskManager.doRunAndWait

Comment (wangmingliang-ms) [reply PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azuretools/ijidea/actions/SelectSubscriptionsAction.java]: reverted since the root cause is not here,

**Review by wangmingliang-ms — APPROVED** [review]

**Review by andxu — APPROVED** [review]
