### PR TITLE
Fix NPE in FunctionRunState and add validation for function run time

### LINKED ISSUE #4532: [IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
IntelliJ build version: 2020.2 IU-202.6397.94
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.40.0-2020.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x964,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.io.IOException: Cannot run program "func" (in directory "/Users/mingli/IdeaProjects/azure-function-examples/target/azure-functions/azure-function-examples-1596612498166"): error=2, No such file or directory
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:120)

### PR DESCRIPTION
**Pull request by Flanker32**
Fix NPE in `FunctionRunState` and add validation for function run time, fixes #4532

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/functions/localrun/FunctionRunState.java [hunk 1]
```diff
@@ -107,17 +127,72 @@ private void launchDebugger(final Project project, int debugPort) {
...
+                throw new AzureExecutionException(FUNCTION_CORE_TOOLS_OUT_OF_DATE);
+            }
+        } catch (IOException | InterruptedException e) {
+            processHandler.setText(String.format(FAILED_TO_VALIDATE_FUNCTION_RUNTIME, e.getMessage()));
+        }
+    }
+
+    private ComparableVersion getFuncVersion() throws IOException, InterruptedException {
+        final String[] funcVersionResult = CommandUtils.executeMultipleLineOutput(
+                String.format("%s -v", functionRunConfiguration.getFuncPath()), null);
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/functions/localrun/FunctionRunState.java:170]: String.format("%s -v... will cause the func -v not work when the path contains spaces.
