### PR TITLE
Fix NPE issues in telemetry

### LINKED ISSUE #4657: [IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException
IntelliJ build version: 2020.2.3 IU-202.7660.26
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.43.0-2020.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.intellij.actions.functions.RunFunctionAction.runConfiguration(RunFunctionAction.java:67)
	at com.microsoft.intellij.actions.functions.RunFunctionAction.lambda$onActionPerformed$0(RunFunctionAction.java:57)
```

### PR DESCRIPTION
**Pull request by Flanker32**
Fix NPE issues in telemetry, fixes #4657

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/functions/library/function/DeployFunctionHandler.java [hunk 1]
```diff
@@ -93,17 +93,16 @@
             + "function information (Attempt %d/%d)...";
 
     private static final OperatingSystemEnum DEFAULT_OS = OperatingSystemEnum.Windows;
-    private IAppServiceContext ctx;
+    private FunctionDeployModel ctx;
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/functions/library/function/DeployFunctionHandler.java:96]: rename the field

**Review by andxu — APPROVED** [review]

**Review by shenqianjin — APPROVED** [review]
