### PR TITLE
Validate data file before init telemetry

### LINKED ISSUE #4490: [IntelliJ][ReportedByUser] Uncaught Exception Error org.xml.sax.SAXParseException; systemId: file:/C:/Users/Gopichaithanya/AppData/Roaming/JetBrains/IdeaIC2020.1/plugins/azure-toolkit-for-intellij/data.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
IntelliJ build version: 2020.1.2 IC-201.7846.76
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1281x690,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error, throwable=org.xml.sax.SAXParseException; systemId: file:/C:/Users/Gopichaithanya/AppData/Roaming/JetBrains/IdeaIC2020.1/plugins/azure-toolkit-for-intellij/data.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at com.microsoft.azuretools.azurecommons.util.ParserXMLUtility.parseXMLFile(ParserXMLUtility.java:70)
	at com.microsoft.intellij.AzurePlugin.setValues(AzurePlugin.java:255)
	at com.microsoft.intellij.AzurePlugin.initializeTelemetry(AzurePlugin.java:163)
	at com.microsoft.intellij.AzurePlugin.runActivity(AzurePlugin.java:128)
``

### PR DESCRIPTION
**Pull request by Flanker32**
Validate data file before init telemetry, fixes #4490 #2525

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/AzurePlugin.java [hunk 1]
```diff
@@ -220,6 +220,19 @@ public void uninstall(@NotNull IdeaPluginDescriptor ideaPluginDescriptor) {
         }
     }
 
+    private boolean isDataFileValid() {
+        final File file = new File(dataFile);
+        if (!file.exists()) {
+            return false;
+        }
+        try {
+            final Document doc = ParserXMLUtility.parseXMLFile(dataFile);
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/AzurePlugin.java:229]: remove "final Document doc = "
