### PR TITLE
Fix IntelliJ regression issues

### LINKED ISSUE #4414: Always show the first webapp although create new webapp
#### Environment:
- OS: Win/Mac
- Plugins Version: Azure java toolkit for IntelliJ: 3.37.0
- IDE Version: IC2020.1-jre11/IU2019.3-jre11

#### Repro steps:
1. Right click your project select Azure > Deploy to Azure Web Apps
2. Create new Webapp

#### Result:
Show the first webapp in webapps list, not new webapp that you just created.
image

### LINKED ISSUE #4417: Cannot docker run
#### Environment:
OS: Win
Plugins Version: Azure java toolkit for IntelliJ: 3.37.0
IDE Version: IU2019.3-jre11
#### Repro steps:
1. Right click your project select Azure > Docker run
#### Result:
image
Error logs:
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList com.spotify.docker.client.messages.Container.ports()'
	at com.microsoft.intellij.runner.container.dockerhost.DockerHostRunState.executeSteps(DockerHostRunState.java:151)
	at com.microsoft.intellij.runner.container.dockerhost.DockerHostRunState.executeSteps(DockerHostRunState.java:55)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:70)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
```

#### Expected:
image

### PR DESCRIPTION
**Pull request by Flanker32**
-Fix can not switch to new create app service issue fixes #4414 
-Fix run docker issue fixes #4417

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/webapp/webappconfig/slimui/WebAppSlimSettingPanel.java [hunk 1]
```diff
@@ -271,17 +271,18 @@ public synchronized void fillWebApps(List<ResourceEx<WebApp>> webAppLists) {
...
-            final ResourceEx<WebApp> selectWebApp = sortedWebAppLists
-                    .stream()
-                    .filter(webAppResourceEx -> StringUtils.equals(webAppResourceEx.getResource().id(), targetId))
-                    .findFirst()
-                    .orElse(sortedWebAppLists.get(0));
-            cbxWebApp.setSelectedItem(selectWebApp);
+            String targetId = webAppConfiguration.getWebAppId();
+            if (StringUtils.isEmpty(targetId) && selectedWebApp != null) {
+                // Use when user cancel create app service
+                targetId = selectedWebApp.getResource().id();
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/webapp/webappconfig/slimui/WebAppSlimSettingPanel.java:277]: only need to change targetId logic, no need to make big changes.
