### PR TITLE
Disable submit job action when cluster is not stable

### LINKED ISSUE #2419: [IntelliJ][Spark on ADL] The cluster in submit job dialog is wrong when the cluster is not stable
Build: Develop 880

Repro Steps:
1. Provision a new cluster named "zzz"
2. Right click on the cluster and click "Submit Job", the config dialog launched.

Result:
image

### PR DESCRIPTION
**Pull request by t-rufang**
To address #2419

### CODE REVIEW

File: Utils/hdinsight-node-common/src/com/microsoft/azure/cosmosspark/serverexplore/cosmossparknode/CosmosSparkClusterNode.java [hunk 1]
```diff
@@ -79,9 +81,12 @@ protected void updateNodeNameAfterLoading() {
     @Override
     protected void loadActions() {
         super.loadActions();
+
         String suffix = "/?adlaAccountName=" + adlAccount.getName();
-        addAction("Submit Job", new CosmosSparkSubmitAction(
-                this, cluster, CosmosSparkClusterOps.getInstance().getSubmitAction()));
+        NodeAction submitCosmosSparkJobAction = addAction(SUBMIT_COSMOS_SPARK_JOB_ACTION_NAME,
+                new CosmosSparkSubmitAction(this, cluster, CosmosSparkClusterOps.getInstance().getSubmitAction()));
+        submitCosmosSparkJobAction.setEnabled(isClusterStable());
```
Comment (wezhang) [inline Utils/hdinsight-node-common/src/com/microsoft/azure/cosmosspark/serverexplore/cosmossparknode/CosmosSparkClusterNode.java]: Could you change the presentation in `CosmosSparkSubmitAction`?

Comment (t-rufang) [reply Utils/hdinsight-node-common/src/com/microsoft/azure/cosmosspark/serverexplore/cosmossparknode/CosmosSparkClusterNode.java]: `CosmosSparkSubmitAction` is of `NodeActionListener` type rather than `NodeAction` type, which means there is no `setEnabled()` method in `CosmosSparkSubmitAction`

---
In reply to: [240597908](https://github.com/Microsoft/azure-tools-for-java/pull/2487#discussion_r240597908) [](ancestors = 240597908)
