### PR TITLE
Fix issues in IntelliJ End game

### LINKED ISSUE #4452: Can't skip creating application insights while creating new function app
### Environment:

- OS: Win 10/Mac 10.15.4
- IDE: IU19.3 - jre11/IU20.1-jre11
- Plugins Version: Azure java toolkits for IntelliJ 3.38.0

### Repro Steps：

1. Create a function project
2. Add azure function deploy configurations
3. Click `Create Function App...` and select `No` for `Enable Application Insights`
4. Deploy function app

### Actual result:
image

### LINKED ISSUE #4454: Cannot refresh after switch app properties window
### Environment:
 - OS: Win 10/Mac 10.15.4
 - IDE: IU19.3 - jre11/IU20.1-jre11
 - Plugins Version: Azure java toolkits for IntelliJ 3.38.0
### Repro Steps：
1. Deploy two apps to azure spring cloud
2. In azure explorer, right click two apps -> Show Properties
3. Switch to the first app properties window
### Actual result:
It cannot refresh to the right page
image

### PR DESCRIPTION
**Pull request by Flanker32**
- Fix always creating application insights issue fixes #4452
- Fix spring cloud properties refresh issue fixes #4454

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/functions/deploy/ui/creation/FunctionCreationDialog.java [hunk 1]
```diff
@@ -251,6 +251,14 @@ private void toggleApplicationInsights(boolean enable) {
         pack();
     }
 
+    private boolean isEnableApplicationInsights() {
```
Comment (andxu) [inline PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/functions/deploy/ui/creation/FunctionCreationDialog.java:254]: enableApplicationInsights
